"""empty message

Revision ID: 95fcc367251d
Revises: 3179067487b2
Create Date: 2017-10-26 18:03:17.719496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95fcc367251d'
down_revision = '3179067487b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Book_Photos_image_name'), 'Book_Photos', ['image_name'], unique=False)
    op.create_index(op.f('ix_Book_Photos_path'), 'Book_Photos', ['path'], unique=False)
    op.drop_index('ix_Book_Photos_image_name', table_name='Book_Photos')
    op.drop_index('ix_Book_Photos_path', table_name='Book_Photos')
    op.create_index(op.f('ix_Books_author'), 'Books', ['author'], unique=False)
    op.create_index(op.f('ix_Books_book_count'), 'Books', ['book_count'], unique=False)
    op.create_index(op.f('ix_Books_name'), 'Books', ['name'], unique=False)
    op.create_index(op.f('ix_Books_publication_date'), 'Books', ['publication_date'], unique=False)
    op.create_index(op.f('ix_Books_rating'), 'Books', ['rating'], unique=False)
    op.create_index(op.f('ix_Books_review'), 'Books', ['review'], unique=False)
    op.drop_index('ix_Books_author', table_name='Books')
    op.drop_index('ix_Books_book_count', table_name='Books')
    op.drop_index('ix_Books_name', table_name='Books')
    op.drop_index('ix_Books_publication_date', table_name='Books')
    op.drop_index('ix_Books_rating', table_name='Books')
    op.drop_index('ix_Books_review', table_name='Books')
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=False)
    op.create_index(op.f('ix_Users_first_name'), 'Users', ['first_name'], unique=False)
    op.create_index(op.f('ix_Users_last_name'), 'Users', ['last_name'], unique=False)
    op.create_index(op.f('ix_Users_username'), 'Users', ['username'], unique=False)
    op.drop_index('ix_Users_email', table_name='Users')
    op.drop_index('ix_Users_first_name', table_name='Users')
    op.drop_index('ix_Users_last_name', table_name='Users')
    op.drop_index('ix_Users_username', table_name='Users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_Users_username', 'Users', ['username'], unique=False)
    op.create_index('ix_Users_last_name', 'Users', ['last_name'], unique=False)
    op.create_index('ix_Users_first_name', 'Users', ['first_name'], unique=False)
    op.create_index('ix_Users_email', 'Users', ['email'], unique=False)
    op.drop_index(op.f('ix_Users_username'), table_name='Users')
    op.drop_index(op.f('ix_Users_last_name'), table_name='Users')
    op.drop_index(op.f('ix_Users_first_name'), table_name='Users')
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.create_index('ix_Books_review', 'Books', ['review'], unique=False)
    op.create_index('ix_Books_rating', 'Books', ['rating'], unique=False)
    op.create_index('ix_Books_publication_date', 'Books', ['publication_date'], unique=False)
    op.create_index('ix_Books_name', 'Books', ['name'], unique=False)
    op.create_index('ix_Books_book_count', 'Books', ['book_count'], unique=False)
    op.create_index('ix_Books_author', 'Books', ['author'], unique=False)
    op.drop_index(op.f('ix_Books_review'), table_name='Books')
    op.drop_index(op.f('ix_Books_rating'), table_name='Books')
    op.drop_index(op.f('ix_Books_publication_date'), table_name='Books')
    op.drop_index(op.f('ix_Books_name'), table_name='Books')
    op.drop_index(op.f('ix_Books_book_count'), table_name='Books')
    op.drop_index(op.f('ix_Books_author'), table_name='Books')
    op.create_index('ix_Book_Photos_path', 'Book_Photos', ['path'], unique=False)
    op.create_index('ix_Book_Photos_image_name', 'Book_Photos', ['image_name'], unique=False)
    op.drop_index(op.f('ix_Book_Photos_path'), table_name='Book_Photos')
    op.drop_index(op.f('ix_Book_Photos_image_name'), table_name='Book_Photos')
    # ### end Alembic commands ###
